version: 0.2

phases:
  install:
    commands:
      - echo "Ensure Docker is available"
      - docker --version # This command is just to ensure Docker is installed and available
  build:
    commands:
      # Build your Docker image
      - docker build -t postman-writer .
      # Run the Postman collection using Newman in the container
      - >
        docker run --rm
        -e DATA_FILE=jokes.csv
        -e RAPIDAPI_KEY=$RAPIDAPI_KEY
        -v "$(pwd):/app"
        postman-writer /bin/sh -c "ls -la /app/reports"
        
artifacts:
  files:
    - reports/junitFullReport.xml
reports:
  junit:
    files:
      - reports/junitFullReport.xml
    file-format: "xml"
    base-directory: 'reports'