version: 0.2

phases:
  install:
    commands:
      - echo "Ensure Docker is available"
      - docker --version # This command is just to ensure Docker is installed and available
  build:
    commands:
      #- mkdir reports
      - docker login --username kappagaa --password $DOCKER_AUTH_PASS
      # Build your Docker image
      - docker pull postman/newman
      # Run the Postman collection using Newman in the container
      - docker run --rm -v "$(pwd):/etc/newman" --entrypoint /bin/sh postman/newman -c "npm i -g newman-reporter-junitfull; newman run postman-writer.postman_collection.json --environment=postman-writer.postman_environment.json --env-var rapidApiKey_evar=$RAPIDAPI_KEY -r junitfull --reporter-junitfull-export './reports/junitFullReport.xml'"
        
artifacts:
  files:
    - reports/junitFullReport.xml
reports:
  junit:
    files:
      - reports/junitFullReport.xml